/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebRouteImport } from './routes/web'
import { Route as WebIndexRouteImport } from './routes/web.index'
import { Route as WebConfiguraRouteImport } from './routes/web.configura'
import { Route as WebRecetasRouteImport } from './routes/web.recetas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRoute,
} as any)
const WebConfiguraRoute = WebConfiguraRouteImport.update({
  id: '/configura',
  path: '/configura',
  getParentRoute: () => WebRoute,
} as any)
const WebRecetasRoute = WebRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => WebRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/web': typeof WebRouteWithChildren
  '/web/configura': typeof WebConfiguraRoute
  '/web/recetas': typeof WebRecetasRoute
  '/web/': typeof WebIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/web/configura': typeof WebConfiguraRoute
  '/web/recetas': typeof WebRecetasRoute
  '/web': typeof WebIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/web': typeof WebRouteWithChildren
  '/web/configura': typeof WebConfiguraRoute
  '/web/recetas': typeof WebRecetasRoute
  '/web/': typeof WebIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/web' | '/web/configura' | '/web/recetas' | '/web/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/web/configura' | '/web/recetas' | '/web'
  id: '__root__' | '/' | '/web' | '/web/configura' | '/web/recetas' | '/web/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WebRoute: typeof WebRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web/': {
      id: '/web/'
      path: '/'
      fullPath: '/web/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/configura': {
      id: '/web/configura'
      path: '/configura'
      fullPath: '/web/configura'
      preLoaderRoute: typeof WebConfiguraRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/recetas': {
      id: '/web/recetas'
      path: '/recetas'
      fullPath: '/web/recetas'
      preLoaderRoute: typeof WebRecetasRouteImport
      parentRoute: typeof WebRoute
    }
  }
}

interface WebRouteChildren {
  WebConfiguraRoute: typeof WebConfiguraRoute
  WebRecetasRoute: typeof WebRecetasRoute
  WebIndexRoute: typeof WebIndexRoute
}

const WebRouteChildren: WebRouteChildren = {
  WebConfiguraRoute: WebConfiguraRoute,
  WebRecetasRoute: WebRecetasRoute,
  WebIndexRoute: WebIndexRoute,
}

const WebRouteWithChildren = WebRoute._addFileChildren(WebRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WebRoute: WebRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
